# To check the rules: https://realm.github.io/SwiftLint/rule-directory.html

disabled_rules:
  - nesting

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_none_name
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - identifier_name
  - first_where
  - force_unwrapping
  - flatmap_over_map_reduce
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - legacy_random
  - mark
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiline_arguments_brackets
  - nimble_operator
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - strict_fileprivate
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

identifier_name:
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - x
    - y
    - z
    - to
    - me

file_header:
  required_pattern: |
                    \/\/
                    \/\/  Copyright \(c\) 2011-2025, Voximplant, Inc\. All rights reserved\.
                    \/\/
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50

large_tuple: 4

type_body_length:
    warning: 600
    error: 1000

file_length:
    warning: 600
    error: 1000

number_separator:
  minimum_length: 5

cyclomatic_complexity:
    warning: 18
    error: 20

force_cast: warning
force_try: warning
function_body_length:
    warning: 100

legacy_hashing: error

function_parameter_count:
    warning: 7
    error: 8
    ignores_default_parameters: true

line_length:
  warning: 135
  error: 200
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 1
