default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :deploy do
    increment_build_number(
      xcodeproj: "ios-sdk-v3-demo.xcodeproj"
    )
    
    build_app(
      project: "ios-sdk-v3-demo.xcodeproj",
      scheme: "ios-sdk-v3-demo",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        provisioningProfiles: {},
        signingStyle: "automatic",
        teamID: ENV['APPSTORE_ISSUER_ID']
      },
      xcargs: "-allowProvisioningUpdates -skipPackagePluginValidation -authenticationKeyPath #{File.expand_path('../AuthKey_' + ENV['APPSTORE_KEY_ID'] + '.p8')} -authenticationKeyID #{ENV['APPSTORE_KEY_ID']} -authenticationKeyIssuerID #{ENV['APPSTORE_ISSUER_ID']}"
    )
    
    upload_to_testflight(
      api_key_path: "../app_store_connect_api_key.json"
    )
  end
end
