default_platform(:ios)

platform :ios do
  desc "Push a new build to TestFlight"
  lane :deploy do
    project_dir = ENV['PROJECT_DIR']
    xcodeproj = "#{project_dir}/#{ENV['XCODEPROJ']}"
    scheme = ENV['SCHEME']
    bundle_id = ENV['BUNDLE_ID']

    increment_build_number(xcodeproj: xcodeproj)
    
    build_app(
      project: xcodeproj,
      scheme: scheme,
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        provisioningProfiles: {
          bundle_id => ENV['PROFILE_UUID']
        }
      },
      xcargs: "-skipPackagePluginValidation " \
              "-skipMacroValidation " \
              "-authenticationKeyPath #{File.expand_path('../AuthKey_' + ENV['APPSTORE_KEY_ID'] + '.p8')} " \
              "-authenticationKeyID #{ENV['APPSTORE_KEY_ID']} " \
              "-authenticationKeyIssuerID #{ENV['APPSTORE_ISSUER_ID']} " \
              "CODE_SIGN_STYLE=Manual " \
              "CODE_SIGN_IDENTITY='Apple Distribution: Zingaya, Inc. (W9BHJBL635)' " \
              "PROVISIONING_PROFILE=#{ENV['PROFILE_UUID']} " \
              "SWIFT_PACKAGE_PLUGINS=NO"
    )
    
    upload_to_testflight(
      api_key: app_store_connect_api_key(
        key_id: ENV['APPSTORE_KEY_ID'],
        issuer_id: ENV['APPSTORE_ISSUER_ID'],
        key_filepath: File.expand_path('../AuthKey_' + ENV['APPSTORE_KEY_ID'] + '.p8')
      )
    )
  end
end
