name: Deploy Audio Call

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/deploy-testflight.yml
    with:
      project_dir: AudioCall
      xcodeproj: audio-call.xcodeproj
      scheme: audio-call
      bundle_id: com.voximplant.demos.v3.audiocall
    secrets:
      CERTIFICATES_P12: ${{ secrets.CERTIFICATES_P12 }}
      CERTIFICATES_PASSWORD: ${{ secrets.CERTIFICATES_PASSWORD }}
      PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE_AUDIOCALL }}
      APPSTORE_PRIVATE_KEY: ${{ secrets.APPSTORE_PRIVATE_KEY }}
      APPSTORE_KEY_ID: ${{ secrets.APPSTORE_KEY_ID }}
      APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
